format = """
$hostname\
$directory\
$git_branch\
$cmd_duration\
$line_break\
$conda\
$character"""

add_newline = false

[hostname]
style = "218"
format = '[$hostname]($style) '

[conda]
format = '[$symbol$environment](dimmed green) '

[directory]
truncation_length = 0
truncate_to_repo = false
style = "blue"

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[❮](bold green)"

[git_branch]
style = "bright-cyan"
format = "[$symbol$branch]($style) "

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

