#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
ratio       = [1, 3, 5]
linemode    = "size"
show_hidden = true
sort_by     = "natural"

[preview]
tab_size   = 2
max_width  = 3000
max_height = 2400

[[plugin.prepend_previewers]]
mime = "image/{jpeg,png,webp}"
run  = "zoom 5"

[opener]
edit = [
  { run = "${EDITOR:-vim} %s", desc = "edit", for = "unix", block = true },
]
